// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAtF3AhzbqidX16IGQQmpvf4231q3scAI',
    appId: '1:1055672475314:web:e0cc2334a3d8007c2b33ab',
    messagingSenderId: '1055672475314',
    projectId: 'civic-voice-1cf5b',
    authDomain: 'civic-voice-1cf5b.firebaseapp.com',
    storageBucket: 'civic-voice-1cf5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDWSkWbz9AkQFtWr91WXlB6_8O6DF0Z6s',
    appId: '1:1055672475314:android:145b306c86d000f32b33ab',
    messagingSenderId: '1055672475314',
    projectId: 'civic-voice-1cf5b',
    storageBucket: 'civic-voice-1cf5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOn7dAG8gHNqUAtmXRbCHGjL8Wg1cocOI',
    appId: '1:1055672475314:ios:19f46b0ca396e64f2b33ab',
    messagingSenderId: '1055672475314',
    projectId: 'civic-voice-1cf5b',
    storageBucket: 'civic-voice-1cf5b.firebasestorage.app',
    iosBundleId: 'com.example.civicVoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOn7dAG8gHNqUAtmXRbCHGjL8Wg1cocOI',
    appId: '1:1055672475314:ios:19f46b0ca396e64f2b33ab',
    messagingSenderId: '1055672475314',
    projectId: 'civic-voice-1cf5b',
    storageBucket: 'civic-voice-1cf5b.firebasestorage.app',
    iosBundleId: 'com.example.civicVoice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAtF3AhzbqidX16IGQQmpvf4231q3scAI',
    appId: '1:1055672475314:web:90be054457ebf7582b33ab',
    messagingSenderId: '1055672475314',
    projectId: 'civic-voice-1cf5b',
    authDomain: 'civic-voice-1cf5b.firebaseapp.com',
    storageBucket: 'civic-voice-1cf5b.firebasestorage.app',
  );
}
